#
# >>> DON'T CHANGE THIS FILE. <<<
# 
# Copy this file as Makefile.mine and set the variables in that copy. The 
# Makefile.mine will be included by the root Makefile, but ignored by git.
#

#
# Program to build.
#
PROJ ?= ej5